In [3]:
a = 33
b = 9
c = 2.0



In [4]:
a+b

42

In [5]:
print(a+b)

42


In [6]:
type(a)

int

In [7]:
type(c)

float

In [10]:
a = 'hello'
type(a)

str

In [25]:
#les entiers pairs de 1 à 10
for i in range(1,11) : 
    if i%2 == 0 :
        print(i)

2
4
6
8
10


List

In [40]:
l = [1,2,3,4,4]

In [41]:
#len, max et min
print('longueur de la liste =', len(l))
print("Valeur max de l =", max(l))
print("Valeur min de l =", min(l))

longueur de la liste = 5
Valeur max de l = 4
Valeur min de l = 1


Ajout d'un élément à une liste

In [42]:
l.append(6)
l

[1, 2, 3, 4, 4, 6]

In [43]:
l = l + [7]
l

[1, 2, 3, 4, 4, 6, 7]

Modifier un élément

In [44]:
l[0] = 29
l

[29, 2, 3, 4, 4, 6, 7]

In [45]:
l.insert(1,9)
l

[29, 9, 2, 3, 4, 4, 6, 7]

Suppression des éléments d'une liste 

In [46]:
l.remove(7)
l

[29, 9, 2, 3, 4, 4, 6]

In [47]:
l.pop(2)

2

In [48]:
l

[29, 9, 3, 4, 4, 6]

Trier une liste 

In [49]:
l.sort(reverse=True)

In [50]:
print(l)

[29, 9, 6, 4, 4, 3]


In [51]:
l_sorted = sorted(l)
print('Sorted list:', l_sorted)



Sorted list: [3, 4, 4, 6, 9, 29]


Liste non homogène

In [52]:
l = [1, 'un', 2]
l.append('deux')
l += [3, 'trois']
print(type(l))
l

<class 'list'>


[1, 'un', 2, 'deux', 3, 'trois']

In [53]:
a = l[3], l[-1]
print(type(a))
a

<class 'tuple'>


('deux', 'trois')

In [54]:
a[0]



'deux'

In [55]:
[2**p for p in range(10)] # "Compréhension de liste"
#creation de la liste [2**0, 2**1, ..., 2**9]

[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]

In [57]:
#lisste des entiers pairs de 1 à 10
l = [i for i in range(1,11) if i%2 == 0]
print(l)

[2, 4, 6, 8, 10]


Tuple

In [58]:


p = tuple(range(1,5))
print("p=", p)
print("p[0] = ", p[0])



p= (1, 2, 3, 4)
p[0] =  1


In [59]:
p = ([1,2],5)

print(p)

p[0][0] = 8

print(p)



([1, 2], 5)
([8, 2], 5)


In [60]:
# Les éléments du tuple sont fixes
p[0] = 6
#on ne peut   pas mmodifier le contenu


TypeError: 'tuple' object does not support item assignment

In [61]:
p1 = (1,2)
p2 = (2,1)

print(p1 == p2)



False


Set

In [62]:
s = set((1,2,'l'))
print(s)

s = {4,5,9,9,9,9}
print(s)



{'l', 1, 2}
{9, 4, 5}


In [63]:
#Ajout d'un élément au set
s.add(6)
print(s)



{9, 4, 5, 6}


In [64]:
#Suppression d'un élément du set
s.discard(5)
print(s)



{9, 4, 6}


In [65]:
s.clear()
print(s)


set()


In [66]:
A = {1,2,3,4,5}
B = {2,4,6,7}
C = {1,2,3}



In [67]:
#Intersection
print("Intersection de A et B =", A&B)

#Union
print("Union entre A et B =", A|B)

#Exclusion
print("Exclusion de B de A =", A-B)

#Différence symétrique
print("Diff sym. A et B =", A^B)



Intersection de A et B = {2, 4}
Union entre A et B = {1, 2, 3, 4, 5, 6, 7}
Exclusion de B de A = {1, 3, 5}
Diff sym. A et B = {1, 3, 5, 6, 7}


In [68]:
print("B est inclus strict dans A") if A>B else print(False)
print("C est inclus dans A") if A>=C else print(False)



False
C est inclus dans A


In [69]:
# 1ère façon de créer un dictionnaire
dic = {"key1": "value1", "answer": 42}
# 2ème façon de créer un dictionnaire
dic2 = dict(key1="value1", answer=42)
# 3ème façon de créer un dictionnaire
dic3 = dict([("key1","value1"), ("answer",42)])
print(dic)
print(dic2)
print(dic3)

dic["answer"]

{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}
{'key1': 'value1', 'answer': 42}


42

In [70]:


dic['new'] = [1,2,3]



In [71]:
dic.keys()

dict_keys(['key1', 'answer', 'new'])

In [72]:
dic.items()

dict_items([('key1', 'value1'), ('answer', 42), ('new', [1, 2, 3])])

In [73]:
dic.values()

dict_values(['value1', 42, [1, 2, 3]])

In [74]:


a,b,c = dic.items()
print(a)



('key1', 'value1')


Programmation Orientée Objet

In [75]:
"""
Exemple de classe en Python
"""
class Moteur:
    
    # Constructeur
    def __init__(self, esn, panne=False):
        self.esn = esn
        self.panne = panne
    
    # Méthodes
    def dire_bonjour(self):
        print('Bonjour, mon numéro de série est ' + self.esn)
    
    def fonctionne(self):
        return not self.panne

In [76]:
mot1 = Moteur('420912')
mot2 = Moteur(panne=True, esn='420913')

mot1.dire_bonjour()
print(mot1.fonctionne())

mot1.panne = True
print(mot1.fonctionne())

print('\n')
mot2.dire_bonjour()
print(mot2.fonctionne())

Bonjour, mon numéro de série est 420912
True
False


Bonjour, mon numéro de série est 420913
False


In [77]:
# Méthode récursive
def fact1(n):
    if n == 0:
        return 1
    else:
        return n*fact1(n-1)

# Méthode itérative
def fact2(n):
    s=1
    for i in range(1,n+1):
        s*=i
    return s

print(fact1(5))
print(fact2(5))



120
120


In [78]:
"""
App.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.
"""



'\nApp.1 : Ecrire une fonction qui retourne le plus grand commun diviseur (pgcd) entre deux nombres a et b.\n'

In [80]:
"""
App.1 : Correction
"""

#Méthode itérative
def pgcd1(a,b):
    while (a%b) != 0:
        s = a%b
        a = b
        b = s
    return b


#Méthode récurcive
def pgcd2(a,b):
    if a==b : return a 
    if a<b : a,b = b,a
    return pgcd2(a-b,b)

a = 230
b = 25

print("pgcd1(a,b) = ", pgcd1(a,b))
print("pgcd2(a,b) = ", pgcd2(a,b))



pgcd1(a,b) =  5
pgcd2(a,b) =  5


In [81]:
pip install numpy pandas

  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.1/12.1 MB 36.0 MB/s eta 0:00:00MB/s eta 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3/3 [pandas]━━━━━━━━━━━ 2/3 [pandas]
Note: you may need to restart the kernel to use updated packages.


In [83]:
import math



In [84]:
x = 4

print("sqrt(x) =", math.sqrt(x))
print("cos(x) =", math.cos(x))
print("sin(x) =", math.sin(x))
print("factorial(x) =", math.factorial(x))

sqrt(x) = 2.0
cos(x) = -0.6536436208636119
sin(x) = -0.7568024953079282
factorial(x) = 24


In [85]:
import numpy as np



In [86]:
# Création d'un array à partir d'une liste
v = np.array([1.0, 2.0, 3.0])
# Création d'un array de taille (n,m) initialisé à 0
z = np.zeros((3,4))
z



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [87]:
# Taille d'un array
print(z.shape)
print(v.shape)



(3, 4)
(3,)


In [88]:
# Opérations courantes
A = np.ones((3,3)) + np.eye(3)
print('A = ', A)
print('Av = ', np.dot(A,v))
print('3*A = ', 3*A)
print('A*v = ', A*v)
print('A + 1 = ', A+1)
print('A + v = ', A+v)
print('A^2 = ', np.square(A))



A =  [[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
Av =  [7. 8. 9.]
3*A =  [[6. 3. 3.]
 [3. 6. 3.]
 [3. 3. 6.]]
A*v =  [[2. 2. 3.]
 [1. 4. 3.]
 [1. 2. 6.]]
A + 1 =  [[3. 2. 2.]
 [2. 3. 2.]
 [2. 2. 3.]]
A + v =  [[3. 3. 4.]
 [2. 4. 4.]
 [2. 3. 5.]]
A^2 =  [[4. 1. 1.]
 [1. 4. 1.]
 [1. 1. 4.]]


In [89]:
B = np.array([5, 2, 9, 1])

print(np.sort(B))


[1 2 5 9]


In [90]:
import random



In [118]:
# Création d'une matrice aléatoire sous forme de liste de listes
taille = 2
A = [[random.random() for _ in range(taille)] for _ in range(taille)]



In [119]:
print(A)

[[0.7858933458780153, 0.4970223531417386], [0.9512835055253256, 0.0911413421734828]]


In [94]:
"""
EXERCICE - Afficher un tuple contenant les dimensions de la matrice A
"""
#raise NotImplementedError

'\nEXERCICE - Afficher un tuple contenant les dimensions de la matrice A\n'

In [104]:
np.array(A).shape

(2, 2)

In [106]:


"""
EXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python
"""
#raise NotImplementedError



'\nEXERCICE - Implémenter le produit matriciel de 2 matrices sous forme de listes de listes python\n'

In [123]:
def produit(A, B): 
    m, n = len(A), len(A[0])
    n2, p = len(B), len(B[0])

    if n != n2 :
        print("produit impossible ")

    C = [[0 for _ in range(p)] for _ in range(m)]

    for i in range(m):
        for j in range(p):
            for k in range(n):
                C[i][j] += A[i][k] * B[k][j]
    return C

In [124]:
print(produit(A,A))

[[1.0904375175164611, 0.43590584444228625], [0.8343086325169394, 0.4811159106743033]]


In [128]:
# Vérification
assert(produit([[1, 2], [3, 4]], [[1, 2], [3, 4]]) == [[7, 10], [15, 22]])

In [129]:
# Sortons le chronomètre
%timeit produit(A, A)



1.44 μs ± 41.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [130]:
# Et maintenant, avec numpy !
import numpy as np



In [131]:
A2 = np.array(A)
print(A2)



[[0.78589335 0.49702235]
 [0.95128351 0.09114134]]


In [132]:
%timeit np.dot(A, A)

2.86 μs ± 161 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


Exos sur pandas 

In [135]:
import pandas as pd

In [136]:
df_exemple = pd.DataFrame({"ESN": ["E420912", "E420913", "E420914"], "panne": [False, False, True]})
df_exemple

ESN  panne
0  E420912  False
1  E420913  False
2  E420914   True

In [ ]:
# !git clone https://github.com/MadaneA/TDs-statistiques-descriptives.git

In [2]:
import os
os.chdir('TDs_Stat_desc_prof')



In [3]:
os.getcwd()



'/home/morel/Bureau/AS_AD/TDs-statistiques-descriptive/TDs_Stat_desc_prof'

In [5]:
import pandas as pd

In [6]:
# Chargement d'un fichier CSV ou Excel
df = pd.read_csv("./data/Vol010.csv")
# Affichage des 5 premières lignes
df.head()



t EGT_SEL FLIGHT_MOD FMV_SEL HPTC_SEL LPTC_SEL  \
0                  datenum   deg_C          _       _        %        %   
1  15/09/2011 14:25:58.125     NaN        NaN     NaN      NaN      NaN   
2  15/09/2011 14:25:58.375     NaN        NaN     NaN      NaN      NaN   
3  15/09/2011 14:25:58.625     NaN        NaN     NaN      NaN      NaN   
4  15/09/2011 14:25:58.875     NaN        NaN     NaN      NaN      NaN   

  N1_SEL N2_ACTSEL OIL_P OIL_TEMP  ... T25_SEL T3_SEL VBV_SEL VIB_CN1 VIB_CN2  \
0      %     %_RPM   psi        _  ...       _      _     DEG       _       _   
1    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
2    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
3    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   
4    NaN         0   NaN      NaN  ...     NaN    NaN     NaN     NaN     NaN   

  VIB_TN1 VIB_TN2 VSV_SEL  WFM_SEL    XM  
0       _       _     DEG     lb/h  mach  
1     NaN     NaN     NaN      NaN   NaN  
2     NaN     NaN     NaN      NaN   NaN  
3     NaN     NaN     NaN      NaN   NaN  
4     NaN     NaN     NaN  7679.98  0.15  

[5 rows x 26 columns]

In [7]:
#les dims du dataframes 
df.shape

(22945, 26)

In [9]:
"""
EXERCICE - Dimensions d'un DataFrame
Affichez le nombre de colonnes et de ligne du DataFrame (indice : beaucoup de méthodes sont communes entre numpy et pandas)
"""
raise NotImplementedError
print('Nombre de colonnes :', df.size)
print('Nombre de lignes :', len(df))



NotImplementedError: 